### ISSUE TITLE
How to send skeleton coordinates to Openvr?

### ISSUE THREAD

**Issue by NoLoPhe** [SlimeVR/SlimeVR-OpenVR-Driver#16]
Hi!

I made pose estimates from 6 IMUs based on the results of the paper TransPose.
I want it to work with VRchat. How do I do that?

I don't see documentation to send skeleton coordinates to Openvr.

Thankyou!

Link: https://twitter.com/Tn23008624/status/1494618444821839877

**Comment by Eirenliel** [comment]
Hi. If you want to use our driver, I suggest you wait or use the server as a reference. We are working on protocol change, and it will be documented after we are done. If you want to use something simpler, take a look at @ju1ce's AprilTags driver: https://github.com/ju1ce/Simple-OpenVR-Bridge-Driver it uses plain text over windows pipes.

**Comment by ju1ce** [comment]
Oh hey, i have been mentioned :D

Seems like an interesting project, so I would be glad to help out. Getting a connection to steamvr working with the mentioned driver should be fairly simple, but since the driver isnt that well documented either, you can stop by the projects discord to ask any questions: https://discord.gg/7gg33wfGZG .

Looking forward to seeing how it works!

**Comment by NoLoPhe** [comment]
Yes, thanks for the help!

I am working with ju1ce/Mediapipe-VR-Fullbody-Tracking. There is an example with python that is very easy to use.
