### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ItsRogueRen** [SlimeVR/SlimeVR-OpenVR-Driver#2]
Is Linux support possible with these trackers?

**Comment by Eirenliel** [comment]
@ItsRogueRen it's planned!

**Comment by bookercodercooker** [comment]
if you were to add linux support it would be nice to make the drive compatible with 1.14 because if you ever used steamvr on linux....... Yeah also thank you for the hard work i hope the project goes well

**Comment by Semperverus** [comment]
I also would love to see Linux support!

**Comment by AbaiQi** [comment]
I would also like it to be available on Linux.

**Comment by ColdIce1605** [comment]
Any updates on this.
I might try it myself but I have zero knowledge of C++ other than this book I have, that I haven't read in awhile.

**Comment by Jimi-James** [comment]
Hey, I don't mean to rush y'all or anything, just wondering if there's any sort of timetable/estimate on this?

I'm currently debating whether to pre-order the coming wave of SlimeVR hardware, and I want to go all Linux since the most recent VRChat update that added EAC also makes it so the game now blocks my Windows virtual machine, and also makes it so that in-game video players now work on Linux (previously the only aspect of VRChat that wasn't working on Linux).

**Comment by Eirenliel** [comment]
The plan is to add linux support before official slimes ship. There isn't much hurdle to do this, just no one did it yet.

**Comment by TheButlah** [comment]
Getting this to happen would be simple, but none of our current contributors have time for it due to other higher priority tasks. If you are interested in Linux support, we would welcome a PR! It should be very easy.

Simply add a unix socket version of [bridge-windows-pipes.cpp](https://github.com/SlimeVR/SlimeVR-OpenVR-Driver/blob/21a5857a9f607bf815d5bb83000b530618b2f146/src/bridge/bridge-windows-pipes.cpp).

**Comment by ButterscotchV** [comment]
Is this resolved now? There's a socket transport and a release made now.

**Comment by yaomtc** [comment]
Thanks, added to my VR on Linux doc on [Gitlab](https://gitlab.com/vr-on-linux/VR-on-Linux) and [Steam](https://gitlab.com/vr-on-linux/VR-on-Linux).
