### ISSUE TITLE
Report and consume positions in standing space instead of raw space

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-OpenVR-Driver#20]
Floor level is not always 0, this can screw up many functions that rely on it, including auto skeleton calibration. Need to find it in the driver, record it, and use as a base.

**Comment by ButterscotchV** [comment]
Reading from the registry would limit our cross-platform capability, is there no definite path?

**Comment by kitlith** [comment]
It's in the steam config directory, which varies depending on where steam is installed. (`C:\Program Files (x86)\Steam\config\chaperone_info.vrchap` on my system, and many other systems, but not guaranteed to be there.) I say registry because I'm thinking of windows, but the problem exists will require solutions across platforms. If there's a way to query steam for its config location, that'd be nice.

**Comment by TheDevMinerTV** [comment]
My suggestion is: try to find the file you're looking for in the default path for the platform (Windows: `C:\Program Files (x86)\Steam\config\chaperone_info.vrchap`, Linux: `~/.steam/...`, macOS: lol idk) and provide a config option somewhere.

**Comment by ButterscotchV** [comment]
It seems you can actually find the location through OpenVR at `%LocalAppData%\openvr\openvrpaths.vrpath` under the key `config`

**Comment by kitlith** [comment]
@TheDevMinerTV Given that the driver doesn't currently have a way to have config options, I'm tentatively labeling that as out of scope, but useful for the future. Instead, I just want to take that one step further -- instead of just default paths, try to autodetect the path as best as our current knowledge allows. ~~On windows, that means querying the installation path registry key. I don't know what it means on mac or linux yet, which means they can get default paths until we figure out what it means.~~

@ButterscotchV aw heck yeah!

**Comment by TheDevMinerTV** [comment]
@ButterscotchV still doesn't really help under Linux as `%LocalAppData%` isn't a thing under Linux.

**Comment by ButterscotchV** [comment]
> @ButterscotchV still doesn't really help as `%LocalAppData%` isn't a thing under Linux.

On Linux it can be found under either `~/.config/openvr/openvrpaths.vrpath` or `~/.openvr/openvrpaths.vrpath`

**Comment by kitlith** [comment]
So it turns out that Valve already wrote the code for us, and put it in the openvr sdk: https://github.com/ValveSoftware/openvr/blob/master/src/vrcommon/vrpathregistry_public.cpp

**Comment by kitlith** [comment]
Gonna try and write out the whole flow to get the translation between raw and standing universe:
 - Call `CVRPathRegistry_Public::GetPaths`, or `CVRPathRegistry_Public::GetVRPathRegistryFilename` and parse the json ourselves
   - We may need to manually include vrcommon into our driver, or maybe we just need the include file.
 - open and parse the `chaperone_info.vrchap` file in the configuration directory we just found.
 - This file can include multiple chaperones, so query `Prop_CurrentUniverseId_Uint64` on the HMD to match the universeId and find the correct chaperone.
 - Driver can now translate from raw universe to standing universe when reporting, and visa versa when slimevr server sends positions back.

Am I missing anything?
